const CONFIG = {
    titleWeb: "IuuuuuZooooo",
    introTitle: 'Zợ ớiiiiiii',
    introDesc: `^^ Chúc zợ 20 tháng 10 zui zẻ nà, hong quạo nà, cứ xinh đẹp hơn từng phút giây trong lòng anh như này nà.IUUUUUUUUU EMMMMMMM`,
    btnIntro: 'Anh mún nói 1 cái này nựa',
    title: 'Mấy nay có nhìu cái anh làm rùi thêm cả thời tiết ròi các thứ làm zợ hong zui nựa. ',
    desc: 'Anh chin lũi zợ gất nhìu, zợ tha lũi cho anh nhaaaaaa',
    btnYes: 'Bít òi, hong quạo anh nựa. Nhưng mà vẫn hơi zũi, anh lo mà dỗ em đi',
    btnNo: 'HONG, ZŨI TIẾP, ANH LO MÀ DỖ EM',
    question: '^^ YEAHHHHHH, tối anh đền bù cho zợ nhớ, giờ zợ nghỉ ngơi xong tối mình làm gì nạ',
    btnReply: '💗 Iuuuuuuuuuu 💗',
    reply: 'Tối nay mình đi măm măm rùi đi tô màu hoặc coi fim nhá :333',
    mess: '^^ Anh bít òi, em nghỉ ngơi ii, 20 tháng 10 iuuuuu zợ muah muah muahhhhhh',
    messDesc: 'Tối nay nào em dậy hay đói nói anh nhaaa, anh vèo vèo qua liền hong để trễ như hum bữa âuuuuu',
    btnAccept: 'Iuuuu anhhh 💟',
}
